#ifndef _DCC_OPCODE_H_
#define _DCC_OPCODE_H_


// these names can be refered in http://www.ibm.com/support/knowledgecenter/ja/SSLTBW_2.2.0/com.ibm.zos.v2r2.f54em00/ispem115.htm
typedef enum {
    NOP, INCL, DECL, INCSD, DECSD, NEG, NOT, ADDL, SUBL, MULL, DIVL, MODL, LESSL, LSEQL, GRTL, GTEQL, EQUL, NTEQL, ANDL, ORL, BANDL, BORL, BXORL, BNOT, LSHIFTL, RSHIFTL, ADDSD, SUBSD, MULSD, DIVSD, MODSD, LESSSD, LSEQSD, GRTSD, GTEQSD, EQUSD, NTEQSD, ANDSD, ORSD, BANDSD, BORSD, BXORSD, LSHIFTSD, RSHIFTSD, CALL, DEL, JMP, JPT, JPF, EQCMP, LOD, LODC, LDA, LDI, STO, STOC, STOD, ADBR, RET, ASS, ASSV, ASSF, ASVF, ASSC, ASVC, ASSD, ASVD, CPY, VAL, VALC, VALD, LIB, STOP,
} OpCode;

static char *OpCodeStr[] = {
    "NOP", "INCL", "DECL", "INCSD", "DECSD", "NEG", "NOT", "ADDL", "SUBL", "MULL", "DIVL", "MODL", "LESSL", "LSEQL", "GRTL", "GTEQL", "EQUL", "NTEQL", "ANDL", "ORL", "BANDL", "BORL", "BXORL", "BNOT", "LSHIFTL", "RSHIFTL", "ADDSD", "SUBSD", "MULSD", "DIVSD", "MODSD", "LESSSD", "LSEQSD", "GRTSD", "GTEQSD", "EQUSD", "NTEQSD", "ANDSD", "ORSD", "BANDSD", "BORSD", "BXORSD", "LSHIFTSD", "RSHIFTSD", "CALL", "DEL", "JMP", "JPT", "JPF", "EQCMP", "LOD", "LODC", "LDA", "LDI", "STO", "STOC", "STOD", "ADBR", "RET", "ASS", "ASSV", "ASSF", "ASVF", "ASSC", "ASVC", "ASSD", "ASVD", "CPY", "VAL", "VALC", "VALD", "LIB", "STOP",
};

int is_binaryOP(OpCode op);

#endif
